
import React, { useState, useEffect } from 'react';
import { api } from '../services/api';
import { Office, Candidate, Preference, User } from '../types';
import { ISSUE_TAGS } from '../constants';

const Ballot: React.FC = () => {
  const [user, setUser] = useState<User | null>(null);
  const [offices, setOffices] = useState<Office[]>([]);
  const [preferences, setPreferences] = useState<Preference[]>([]);
  const [selectingOffice, setSelectingOffice] = useState<Office | null>(null);
  const [candidates, setCandidates] = useState<Candidate[]>([]);
  const [resolvedCandidates, setResolvedCandidates] = useState<Record<string, Candidate>>({});
  const [searchTerm, setSearchTerm] = useState('');
  const [selectedReasons, setSelectedReasons] = useState<string[]>([]);
  const [copySuccess, setCopySuccess] = useState(false);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    const load = async () => {
      const u = await api.initSession();
      const offs = await api.getOffices();
      const prefs = api.getPreferences();
      setUser(u);
      setOffices(offs);
      setPreferences(prefs);
      
      // Resolve initial chosen candidates names
      const resolved: Record<string, Candidate> = {};
      for (const p of prefs) {
        const cand = await api.getCandidateById(p.candidateId);
        if (cand) resolved[p.candidateId] = cand;
      }
      setResolvedCandidates(resolved);
      setLoading(false);
    };
    load();
  }, []);

  const openSelection = async (office: Office) => {
    if (!user) return;
    setSelectingOffice(office);
    const cands = await api.getCandidates(office.id, user.state, user.lga);
    setCandidates(cands);
    setSearchTerm('');
    setSelectedReasons([]);
  };

  const saveChoice = async (candidateId: string) => {
    if (!selectingOffice || !user) return;
    const prefData = {
      userId: user.id,
      officeId: selectingOffice.id,
      candidateId,
      reasons: selectedReasons
    };
    
    // Optimistic update
    const cand = candidates.find(c => c.id === candidateId);
    if (cand) setResolvedCandidates(prev => ({ ...prev, [candidateId]: cand }));
    
    await api.savePreference(prefData);
    setPreferences(api.getPreferences());
    setSelectingOffice(null);
  };

  const handleShare = async () => {
    if (!user) return;
    let summary = `🗳️ My Village Boy Ballot Summary\n📍 ${user.state} / ${user.lga}\n\n`;
    preferences.forEach(p => {
      const office = offices.find(o => o.id === p.officeId);
      const cand = resolvedCandidates[p.candidateId];
      if (office && cand) summary += `• ${office.name}: ${cand.name} (${cand.party})\n`;
    });
    summary += `\nGenerated by Village Boy - Nigeria's Civic Voice.`;

    if (navigator.share) {
      try {
        await navigator.share({ title: 'My Village Boy Ballot', text: summary, url: window.location.href });
      } catch (err) {}
    } else {
      navigator.clipboard.writeText(summary);
      setCopySuccess(true);
      setTimeout(() => setCopySuccess(false), 2000);
    }
  };

  if (loading) return <div className="flex justify-center py-24"><div className="animate-spin rounded-full h-12 w-12 border-b-2 border-green-600"></div></div>;

  const filteredCandidates = candidates.filter(c => 
    c.name.toLowerCase().includes(searchTerm.toLowerCase()) ||
    c.party.toLowerCase().includes(searchTerm.toLowerCase())
  );

  return (
    <div className="space-y-6 pb-24 animate-in fade-in duration-500">
      <header className="bg-green-600 text-white p-6 rounded-[2rem] shadow-xl shadow-green-100 dark:shadow-green-900/20 space-y-2">
        <div className="flex justify-between items-start">
          <div className="space-y-1">
            <h2 className="text-sm font-bold uppercase tracking-widest opacity-80">My Village Ballot</h2>
            <p className="text-2xl font-bold leading-tight">{user?.state || 'Select State'}, <br/><span className="opacity-70">{user?.lga || 'Select LGA'}</span></p>
          </div>
          <button onClick={handleShare} className="p-3 bg-white/10 rounded-2xl backdrop-blur-sm border border-white/20 hover:bg-white/20 transition-all">
            <svg xmlns="http://www.w3.org/2000/svg" className="h-5 w-5" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M8.684 13.342C8.886 12.938 9 12.482 9 12c0-.482-.114-.938-.316-1.342m0 2.684a3 3 0 110-2.684m0 2.684l6.632 3.316m-6.632-6l6.632-3.316m0 0a3 3 0 105.367-2.684 3 3 0 00-5.367 2.684zm0 9.316a3 3 0 105.368 2.684 3 3 0 00-5.368-2.684z" /></svg>
          </button>
        </div>
        {copySuccess && <p className="text-[10px] bg-white/20 px-2 py-1 rounded text-center animate-bounce">Copied to clipboard!</p>}
      </header>

      <div className="grid grid-cols-1 gap-4">
        {offices.map((office) => {
          const pref = preferences.find(p => p.officeId === office.id);
          const chosen = pref ? resolvedCandidates[pref.candidateId] : null;
          return (
            <div key={office.id} className="bg-white dark:bg-slate-900 p-5 rounded-3xl border border-slate-100 dark:border-slate-800 shadow-sm flex items-center justify-between gap-4 transition-colors">
              <div className="space-y-1">
                <h4 className="text-[10px] font-bold text-slate-400 dark:text-slate-500 uppercase tracking-widest">{office.name}</h4>
                <p className={`font-bold ${chosen ? 'text-slate-900 dark:text-slate-100' : 'text-slate-300 dark:text-slate-700 italic'}`}>{chosen ? chosen.name : 'Unassigned'}</p>
                {chosen && <p className="text-xs text-green-600 dark:text-green-500 font-medium">{chosen.party}</p>}
              </div>
              <button onClick={() => openSelection(office)} className={`shrink-0 w-12 h-12 rounded-2xl flex items-center justify-center transition-all ${chosen ? 'bg-slate-50 dark:bg-slate-800 text-slate-400 dark:text-slate-500 hover:bg-slate-100 dark:hover:bg-slate-700' : 'bg-green-600 text-white shadow-lg shadow-green-100 dark:shadow-green-900/20'}`}>
                {chosen ? <svg xmlns="http://www.w3.org/2000/svg" className="h-5 w-5" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M15.232 5.232l3.536 3.536m-2.036-5.036a2.5 2.5 0 113.536 3.536L6.5 21.036H3v-3.572L16.732 3.732z" /></svg> : <svg xmlns="http://www.w3.org/2000/svg" className="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 4v16m8-8H4" /></svg>}
              </button>
            </div>
          );
        })}
      </div>

      {selectingOffice && (
        <div className="fixed inset-0 z-[60] bg-slate-900/60 dark:bg-black/80 backdrop-blur-sm flex flex-col justify-end">
          <div className="bg-white dark:bg-slate-900 rounded-t-[2.5rem] p-6 max-h-[90vh] overflow-y-auto space-y-6 animate-in slide-in-from-bottom-full duration-300 shadow-2xl">
            <div className="flex justify-between items-center sticky top-0 bg-white dark:bg-slate-900 py-2 z-10 transition-colors">
              <h3 className="text-xl font-bold text-slate-900 dark:text-slate-100">Choose {selectingOffice.name}</h3>
              <button onClick={() => setSelectingOffice(null)} className="p-2 bg-slate-100 dark:bg-slate-800 text-slate-500 dark:text-slate-400 rounded-full"><svg xmlns="http://www.w3.org/2000/svg" className="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" /></svg></button>
            </div>
            <input type="text" placeholder="Search..." className="w-full p-4 rounded-2xl bg-slate-100 dark:bg-slate-800 border-none text-slate-900 dark:text-slate-100 placeholder:text-slate-400 dark:placeholder:text-slate-500 focus:ring-2 focus:ring-green-600 transition-colors" value={searchTerm} onChange={(e) => setSearchTerm(e.target.value)} />
            <div className="space-y-3">
              <h4 className="text-xs font-bold text-slate-400 dark:text-slate-500 uppercase tracking-widest px-1">Candidates</h4>
              {filteredCandidates.map((c) => (
                <div key={c.id} className="p-4 rounded-3xl border border-slate-100 dark:border-slate-800 flex items-center justify-between bg-white dark:bg-slate-900">
                  <div><p className="font-bold text-slate-900 dark:text-slate-100">{c.name}</p><p className="text-xs text-slate-500 dark:text-slate-400">{c.party}</p></div>
                  <button onClick={() => saveChoice(c.id)} className="bg-green-600 text-white px-4 py-2 rounded-xl text-sm font-bold">Select</button>
                </div>
              ))}
            </div>
          </div>
        </div>
      )}
    </div>
  );
};

export default Ballot;
